### ISSUE TITLE
给APP自启动权限就能正常出现APP Updated

### ISSUE THREAD

**Issue by railjty** [vvb2060/PackageInstallerTest#2]
机型：Redmi K40 Gaming
系统版本：Android 12
MIUI版本：21.1.13
操作：授权PackageInstallersTest这个APP自启权限，然后打开bginstall，安装APP
结果：安装完成后出现APP Updated通知，符合预期
所以是小米他们修复了？
编辑：未关闭MIUI优化

**Comment by vvb2060** [comment]
在Android12上，应该能静默更新，所以…没有。

**Comment by railjty** [comment]
> 在Android12上，应该能静默更新，所以…没有。

静默更新这个应该是被禁了，不过以现在的生态这样有好处
